import numpy as np
import os
from pathlib import Path
from spear_path import get_spear_paths
import subprocess
import xarray

from utils import HSMGet, pad_ds, write_ds
from spear_path import SPEAR_ROOT
hsmget = HSMGet(archive=SPEAR_ROOT)


def get_files_to_extract(ystart, mstart, ens):
    files = get_spear_paths(
        ['t_ref'],
        ystart, mstart, 'atmos_daily', 'daily', ens=ens
    )
    return files


def write_atmos(ystart, mstart, ens, work_dir, lat_slice, lon_slice, rerun=False):
    out_dir = work_dir / f'{ystart}-{mstart:02d}-e{ens:02d}'
    if rerun or not out_dir.is_dir():
        # Read mask for flooding
        static = xarray.open_dataset('/scratch/spear/atmos.static.nc')
        is_ocean = np.invert(static.land_mask.astype('bool'))
        print('extract from archive or ptmp')
        extracted_files = hsmget(get_files_to_extract(ystart, mstart, ens))
        print('pad and save')
        tmpdir = Path(os.environ['TMPDIR']) / 'atmos_raw' / f'{ystart}-{mstart:02d}-e{ens:02d}'
        tmpdir.mkdir(exist_ok=True, parents=True)
        for f in extracted_files:
            print('    ' + str(f))
            #open
            ds = (
                xarray.open_dataset(f)
                .sel(lat=lat_slice, lon=lon_slice)
            )
            # Need to mask just the variable of interest and not the
            # coordinate/metadata variables 
            main_var = [x for x in ds.data_vars if len(ds[x].dims)==3][0]
            ds[main_var] = ds[main_var].where(is_ocean)
            padded = pad_ds(ds)
            fout = tmpdir / f.name
            write_ds(padded, fout)
            # cdo doesn't like if the input is also the output here
            subprocess.run([f'cdo -O replace {fout} -setmisstodis,3 -selvar,{main_var} {fout} {fout}.new'], shell=True, check=True)
            # Rename the file generated by cdo to the output file 
            fout.with_suffix(fout.suffix + '.new').rename(fout)

        print('vftmp -> work')
        out_dir.mkdir(exist_ok=True)
        subprocess.run([f'cp {tmpdir}/atmos*.nc {out_dir}'], shell=True, check=True)
    else:
        print(f'Already found data for {out_dir.as_posix()}')



def write_atmos_all_members(ystart, mstart, nens, work_dir, lat_slice, lon_slice, rerun=False):
    # Read mask for flooding
    static = xarray.open_dataset('/scratch/spear/atmos.static.nc')
    is_ocean = np.invert(static.land_mask.astype('bool'))
    members = {}
    for ens in range(1, nens+1):
        out_dir = work_dir / f'{ystart}-{mstart:02d}-e{ens:02d}'
        if rerun or not out_dir.is_dir():
            members.update({ens: get_files_to_extract(ystart, mstart, ens)})

    if len(members) == 0:
        return None

    # dmget everything at once instead of separately by member
    # to reduce the change of dmget failing
    print(f' dmget {len(members)} members')
    all_file_strs = ' '.join(map(lambda x: x.as_posix(), sum(members.values(), [])))
    #subprocess.run(['dmget ' + all_file_strs], shell=True, check=True)
    tmpdir = Path(os.environ['TMPDIR']) / 'atmos_raw' / f'{ystart}-{mstart:02d}-e{ens:02d}'
    tmpdir.mkdir(exist_ok=True, parents=True)

    for ens, source_files in members.items():
        print(f'---{ens:02d}---')
        print('extract from archive or ptmp')
        extracted_files = hsmget(source_files)
        print('pad and save')
        out_dir = work_dir / f'{ystart}-{mstart:02d}-e{ens:02d}'
        for f in extracted_files:
            print('    ' + str(f))
            ds = (
                xarray.open_dataset(f)
                .sel(lat=lat_slice, lon=lon_slice)
            )
            # Need to mask just the variable of interest and not the
            # coordinate/metadata variables 
            main_var = [x for x in ds.data_vars if len(ds[x].dims)==3][0]
            ds[main_var] = ds[main_var].where(is_ocean)
            padded = pad_ds(ds)
            fout = tmpdir / f.name
            write_ds(padded, fout)
            # cdo doesn't like if the input is also the output here
            subprocess.run([f'cdo -O replace {fout} -setmisstodis,3 -selvar,{main_var} {fout} {fout}.new'], shell=True, check=True)
            # Rename the file generated by cdo to the output file 
            fout.with_suffix(fout.suffix + '.new').rename(fout)
            print('vftmp -> work')
            out_dir.mkdir(exist_ok=True)
            subprocess.run([f'cp {tmpdir}/atmos*.nc {out_dir}'], shell=True, check=True)


if __name__ == '__main__':
    import argparse
    from yaml import safe_load
    parser = argparse.ArgumentParser()
    parser.add_argument('-y', '--year', type=int)
    parser.add_argument('-m', '--month', type=int)
    parser.add_argument('-n','--new', action='store_true')
    parser.add_argument('-e', '--ensemble', type=int, default=-1, help='Ensemble member to extract (default -1 extracts all members set by config)')
    parser.add_argument('-c', '--config', type=str, required=True)
    parser.add_argument('-r','--rerun', action='store_true', help='Write even if the files for this run already exist')
    args = parser.parse_args()
    with open(args.config, 'r') as file: 
        config = safe_load(file)
    # Note conversion from [-180, 180] to [0, 360]
    xslice = slice(config['domain']['west_lon'] % 360, config['domain']['east_lon'] % 360)
    yslice = slice(config['domain']['south_lat'], config['domain']['north_lat'])
    work_dir = Path(config['filesystem']['forecast_input_data']) / 'atmos'
    work_dir.mkdir(exist_ok=True)

    if args.ensemble == -1:
        forecast_name = 'new_forecasts' if args.new else 'retrospective_forecasts'
        nens = config[forecast_name]['ensemble_size']
        write_atmos_all_members(args.year, args.month, nens, work_dir, yslice, xslice, rerun=args.rerun)
    elif args.ensemble > 0:
        write_atmos(args.year, args.month, args.ensemble, work_dir, yslice, xslice, rerun=args.rerun)
    

